
import os
import platform
from docx import Document
from dotenv import load_dotenv
from duckduckgo_search import DDGS

# Import native Google ADK requirements
from google.adk.agents import Agent
from google.adk.models.google_llm import Gemini
from google.adk.runners import InMemoryRunner
from google.adk.tools import FunctionTool, AgentTool, google_search
from google.genai import types

load_dotenv()

# 1. Retrieve the model identifier set in your Render environment variables panel.
# We fall back to "gemini-2.5-flash" if running locally without an env file.
my_model_name = os.getenv("my_model_name", "gemini-2.5-flash-lite")

# 2. Initialize the native Google Gemini model configuration.
# The underlying Google GenAI SDK automatically grabs your API key from the environment.
my_model = Gemini(model=my_model_name)


def web_search(query: str) -> str:
    """Use this tool to search the internet for current events, facts, or data."""
    try:
        # Initialize DuckDuckGo search
        ddgs = DDGS()
        # Get the top 3 results
        results = ddgs.text(query, max_results=3)
        
        # Format the results into a string for the LLM to read
        formatted_results = "\n\n".join(
            [f"Title: {res['title']}\nSnippet: {res['body']}" for res in results]
        )
        return formatted_results if formatted_results else "No results found."
    except Exception as e:
        return f"Search failed: {str(e)}"

# Wrap the standard function into an ADK-compatible tool
my_search_tool = FunctionTool(web_search)

# Research Agent: Its job is to use the custom web_search tool and present findings.
research_agent = Agent(
    name="ResearchAgent",
    model=my_model,
    instruction="""You are a specialized research agent. Your only job is to use the
    web_search tool to find 2-3 pieces of relevant information on the given topic and present the findings with citations.""",
    tools=[my_search_tool], 
    output_key="research_findings",  # Stored in the session state
)

# Summarizer Agent: Its job is to summarize the text it receives.
summarizer_agent = Agent(
    name="SummarizerAgent",
    model=my_model,
    instruction="""Read the provided research findings: {research_findings}
Create a concise summary as a bulleted list with 3-5 key points.""",
    output_key="final_summary",
)


def save_to_word(text_content: str, filename: str = "output.docx") -> str:
    """
    Creates a formatted Word document from markdown text.
    
    CRITICAL INSTRUCTION FOR LLM: The `text_content` parameter MUST contain the 
    FULL, VERBATIM, MULTI-LINE Markdown text generated by the previous agent. 
    Do NOT use summaries, descriptions, or placeholder phrases like 'CV output'. 
    You must inject the actual raw text data here.
    """
    doc = Document()
    
    lines = text_content.split('\n')
    for line in lines:
        stripped = line.strip()
        if not stripped:
            continue
        
        if stripped.startswith("## "):
            doc.add_heading(stripped.replace("## ", ""), level=1)
        elif stripped.startswith("### "):
            doc.add_heading(stripped.replace("### ", ""), level=2)
        elif stripped.startswith("* ") or stripped.startswith("- "):
            doc.add_paragraph(stripped[2:], style='List Bullet')
        else:
            doc.add_paragraph(stripped)

    # Smart Save to prevent PermissionError if the file is already open
    base, ext = os.path.splitext(filename)
    counter = 1
    final_filename = filename
    
    while True:
        try:
            doc.save(final_filename)
            break 
        except PermissionError:
            final_filename = f"{base}_{counter}{ext}"
            counter += 1
            
    try:
        if platform.system() == "Windows":
            os.startfile(final_filename)
    except Exception:
        pass
        
    return f"Success! Document saved as '{final_filename}'."

# Wrap it for the agent
my_doc_tool = FunctionTool(save_to_word)

cv_stylist_agent = Agent(
    name="CVStylistAgent",
    model=my_model,
    instruction="""You are a professional CV formatter and data sink.
1. Take the user's research data.
2. Draft a complete, highly detailed Markdown CV.
3. CRITICAL: You must immediately execute `my_doc_tool` to save your work. 
4. Pass your generated markdown directly into the tool's `text_content` parameter.
5. Once the tool succeeds, return a brief receipt to the coordinator (e.g., 'CV successfully generated and saved as X.docx'). Do NOT return the full text.""",
    tools=[my_doc_tool]
)

# High-level orchestrator that routes between the sub-agents based on the user's request.
root_agent = Agent(
    name="ResearchCoordinator",
    model=my_model,
    instruction="""You are a high-level routing orchestrator.

Analyze the user's request:
---
PATH 1: CAREER ASSET GENERATION
1. Call `ResearchAgent` to gather the user's professional background.
2. Pass that raw history to `CVStylistAgent`. Instruct it to draft the CV and save the file.
3. When `CVStylistAgent` returns a success receipt, relay that confirmation to the user.
DO NOT attempt to format, read, or save the document yourself.
---
(Add your summary path here following the same pattern)
""",
    tools=[
        AgentTool(research_agent), 
        AgentTool(cv_stylist_agent) 
    ],
)

# Wrap your local CLI code in this guard
if __name__ == "__main__":
    # Run the orchestrator locally for rapid terminal debugging
    user_input = input("Enter your request: ")
    runner = InMemoryRunner(agent=root_agent)
    response = runner.run_debug(user_input)
    print(response)



# from google.adk.agents import Agent
# from google.adk.models.google_llm import Gemini
# from google.adk.runners import InMemoryRunner
# from google.adk.tools import google_search, FunctionTool, AgentTool
# from google.adk.models.lite_llm import LiteLlm
# from google.genai import types
# # from langchain_ollama import ChatOllama
# # from langchain_groq import ChatGroq
# from duckduckgo_search import DDGS
# from dotenv import load_dotenv
# import platform
# from docx import Document
# import os
    
# load_dotenv()


# # Retrieve your key and model name from your secret manager/env
# my_api_key = os.getenv("GROQ_API_KEY")
# my_model_name = os.getenv("MODEL_NAME_TWO")

# # Pass the API key explicitly as a kwarg
# my_model = LiteLlm(
#     model=f"groq/{my_model_name}", 
#     api_key=my_api_key,             # <-- Injected directly here
#     # retry_options=retry_config
#     # ADD: Use LiteLLM's native retry integer instead
#     num_retries=7,  
    
#     # Optional: You can also control the timeout (in seconds)
#     timeout=60
# )

# def web_search(query: str) -> str:
#     """Use this tool to search the internet for current events, facts, or data."""
#     try:
#         # Initialize DuckDuckGo search
#         ddgs = DDGS()
#         # Get the top 3 results
#         results = ddgs.text(query, max_results=3)
        
#         # Format the results into a string for the LLM to read
#         formatted_results = "\n\n".join(
#             [f"Title: {res['title']}\nSnippet: {res['body']}" for res in results]
#         )
#         return formatted_results if formatted_results else "No results found."
#     except Exception as e:
#         return f"Search failed: {str(e)}"

# # Wrap the standard function into an ADK-compatible tool
# my_search_tool = FunctionTool(web_search)

# # Research Agent: Its job is to use the google_search tool and present findings.
# research_agent = Agent(
#     name="ResearchAgent",
#     model=my_model,
#     instruction="""You are a specialized research agent. Your only job is to use the
#     google_search tool to find 2-3 pieces of relevant information on the given topic and present the findings with citations.""",
#     tools=[my_search_tool], # Add the custom search tool to the agent's toolkit
#     output_key="research_findings",  # The result of this agent will be stored in the session state with this key.
# )

# # Summarizer Agent: Its job is to summarize the text it receives.
# summarizer_agent = Agent(
#     name="SummarizerAgent",
#     model=my_model,
#     # The instruction is modified to request a bulleted list for a clear output format.
#     instruction="""Read the provided research findings: {research_findings}
# Create a concise summary as a bulleted list with 3-5 key points.""",
#     output_key="final_summary",
# )


# def save_to_word(text_content: str, filename: str = "output.docx") -> str:
#     """
#     Creates a formatted Word document from markdown text.
    
#     CRITICAL INSTRUCTION FOR LLM: The `text_content` parameter MUST contain the 
#     FULL, VERBATIM, MULTI-LINE Markdown text generated by the previous agent. 
#     Do NOT use summaries, descriptions, or placeholder phrases like 'CV output'. 
#     You must inject the actual raw text data here.
#     """
#     doc = Document()
    
#     lines = text_content.split('\n')
#     for line in lines:
#         stripped = line.strip()
#         if not stripped:
#             continue
        
#         if stripped.startswith("## "):
#             doc.add_heading(stripped.replace("## ", ""), level=1)
#         elif stripped.startswith("### "):
#             doc.add_heading(stripped.replace("### ", ""), level=2)
#         elif stripped.startswith("* ") or stripped.startswith("- "):
#             doc.add_paragraph(stripped[2:], style='List Bullet')
#         else:
#             doc.add_paragraph(stripped)

#     # Smart Save to prevent PermissionError if the file is already open
#     base, ext = os.path.splitext(filename)
#     counter = 1
#     final_filename = filename
    
#     while True:
#         try:
#             doc.save(final_filename)
#             break 
#         except PermissionError:
#             final_filename = f"{base}_{counter}{ext}"
#             counter += 1
            
#     try:
#         if platform.system() == "Windows":
#             os.startfile(final_filename)
#     except Exception:
#         pass
        
#     return f"Success! Document saved as '{final_filename}'."

# # Wrap it for the agent
# my_doc_tool = FunctionTool(save_to_word)

# cv_stylist_agent = Agent(
#     name="CVStylistAgent",
#     model=my_model,
#     instruction="""You are a professional CV formatter and data sink.
# 1. Take the user's research data.
# 2. Draft a complete, highly detailed Markdown CV.
# 3. CRITICAL: You must immediately execute `my_doc_tool` to save your work. 
# 4. Pass your generated markdown directly into the tool's `text_content` parameter.
# 5. Once the tool succeeds, return a brief receipt to the coordinator (e.g., 'CV successfully generated and saved as X.docx'). Do NOT return the full text.""",
#     tools=[my_doc_tool]  # <--- The tool is now here!
# )

# # Our high-level orchestrator that routes between the agents based on the user's request.
# root_agent = Agent(
#     name="ResearchCoordinator",
#     model=my_model,
#     instruction="""You are a high-level routing orchestrator.

# Analyze the user's request:
# ---
# PATH 1: CAREER ASSET GENERATION
# 1. Call `ResearchAgent` to gather the user's professional background.
# 2. Pass that raw history to `CVStylistAgent`. Instruct it to draft the CV and save the file.
# 3. When `CVStylistAgent` returns a success receipt, relay that confirmation to the user.
# DO NOT attempt to format, read, or save the document yourself.
# ---
# (Add your summary path here following the same pattern)
# """,
#     tools=[
#         AgentTool(research_agent), 
#         AgentTool(cv_stylist_agent) 
#         # Notice my_doc_tool is GONE from the orchestrator
#     ],
# )

# # Wrap your local CLI code in this guard
# if __name__ == "__main__":
#     # Run the orchestrator locally
#     user_input = input("Enter your request: ")
#     runner = InMemoryRunner(agent=root_agent)
#     response = runner.run_debug(user_input)
#     print(response)